### PR TITLE
Made repo work with light & dark mode (Jun 26)

### PR DESCRIPTION
**Pull request by chukwuemekasmba**
- Wrote code for Launch Academy repo to work on light and dark mode with ChakraUI and Sass. (see video)
- Installed NextJs for easy page routing 
- Also installed framer motion (optional) for animations
- Created a navigation component

Still runs on `npm start` or `npm run dev`

Tagging PM & Team Lead for review @Nicolas7Chaves @makeitmvp-product 

https://github.com/makeitMVPadmin/P4_Skill_Exchange/assets/76162087/e1581333-6d54-40cf-b81d-a000a9ed882d

### CODE REVIEW

**Comment by Nicolas7Chaves** [comment]
Hi Emeka, hold off on the Pull requests for dark and light mode until we have solidified our styling with the ruleset assigned by communiti

**Comment by emekathegreat1** [comment]
Alright then.

**Comment by emekathegreat1** [comment]
Hi @Nicolas7Chaves 

Made commits yesterday that include about the same things in this PR but with tailwind instead of ChakraUI, but i'm having issues with loading the fonts i added from the `/public` folder. Would you be willing to take a look?

**Comment by emekathegreat1** [comment]
Hello Again @Nicolas7Chaves 

Requesting *negative* feedback from recent commits

### Changes Made

- Added tailwind & typescript (agreed by the group)
- Made fonts work
- Added color guides according to the design
- Still using NextJS & React 
- Reconstructed navigation component

Would like to know what you don't like about the changes specifically 🙏🏾
Thanks!

https://github.com/makeitMVPadmin/P4_Skill_Exchange/assets/76162087/0ca1db89-9609-4222-a241-f0a03ad64f4a

**Pull request closed without merging**
