### PR TITLE
Lap4 se 114

### PR DESCRIPTION
**Pull request by Bita-Fotovvat**
Changes Implemented:
- Removed “Filter” Text from the top of "Categories"
- Added a dropdown icon (chosen from Icon8) to the assets>icons folder and rendered it on the right side of Categories
- Added a bubble tag that displays the currently selected category below the Categories section.

### CODE REVIEW

**Review by jaskaurbrar14 — APPROVED** [review]
Try to avoid comments in code. there is one comment.

**Comment by Bita-Fotovvat** [comment]
The branch does not have any merge conflicts with develop at this point.

**Comment by Bita-Fotovvat** [comment]
> Try to avoid comments in code. there is one comment.

That is true. Since some comments are reminders for the next velocity I will keep them for now though, and will make sure to remove them after dealing with them.

**Comment by Bita-Fotovvat** [comment]
The branch does not have any merge conflicts with the develop branch, it adds simple features to the category dropdown, and it has been reviewed by another teammate and has been approved.

**Pull request merged**
